use anyhow::{Result, bail};

#[path = "powershell_value.rs"]
mod powershell_value;

pub(crate) use self::powershell_value::parse_value;
use self::powershell_value::{
    assignment, is_generated_positional_binding, parse_argv, parse_pattern, strip_comment,
    validate_name,
};
use super::predicate::parse_powershell_predicate;
use crate::core::transpile::ast::{CaseArm, Item, Program, Statement, Value};
use crate::core::transpile::lower::lower_functions;
use crate::core::transpile::parse_lex::is_valid_name;

#[derive(Debug, Clone)]
struct Line {
    number: usize,
    text: String,
}

struct Parser {
    lines: Vec<Line>,
    index: usize,
}

pub(crate) fn parse_powershell(source: &str) -> Result<Program> {
    Parser::new(source).parse_program()
}

impl Parser {
    fn new(source: &str) -> Self {
        let lines = source
            .lines()
            .enumerate()
            .filter_map(|(index, line)| {
                let text = strip_comment(line).trim().to_string();
                if text.is_empty()
                    || text.starts_with("# Generated by ")
                    || text == "$ErrorActionPreference = 'Stop'"
                    || is_generated_positional_binding(&text)
                {
                    return None;
                }
                Some(Line {
                    number: index + 1,
                    text,
                })
            })
            .collect();
        Self { lines, index: 0 }
    }

    fn parse_program(mut self) -> Result<Program> {
        let mut items = Vec::new();
        while self.peek().is_some() {
            if self
                .peek_text()
                .is_some_and(|text| text.starts_with("function "))
            {
                items.push(self.parse_function()?);
            } else {
                items.push(Item::Statement {
                    statement: self.parse_statement()?,
                });
            }
        }
        Ok(lower_functions(Program { version: 1, items }))
    }

    fn parse_function(&mut self) -> Result<Item> {
        let line = self.next().expect("function line should exist");
        let name = line
            .text
            .strip_prefix("function ")
            .and_then(|text| text.strip_suffix(" {"))
            .ok_or_else(|| anyhow::anyhow!("{}: expected function header", line.number))?;
        validate_name(name, line.number)?;
        let body = self.parse_block(&["}"])?;
        self.expect("}")?;
        Ok(Item::Function {
            name: name.to_string(),
            body,
        })
    }

    fn parse_block(&mut self, terminators: &[&str]) -> Result<Vec<Statement>> {
        let mut body = Vec::new();
        while let Some(line) = self.peek() {
            if terminators
                .iter()
                .any(|terminator| line.text == *terminator)
            {
                break;
            }
            body.push(self.parse_statement()?);
        }
        Ok(body)
    }

    fn parse_statement(&mut self) -> Result<Statement> {
        let Some(line) = self.peek().cloned() else {
            bail!("unexpected end of input");
        };
        if line.text.starts_with("if ") {
            return self.parse_if();
        }
        if line.text.starts_with("while ") {
            return self.parse_while();
        }
        if line.text.starts_with("switch ") {
            return self.parse_switch();
        }
        self.next();
        parse_simple_statement(&line)
    }

    fn parse_if(&mut self) -> Result<Statement> {
        let line = self.next().expect("if line should exist");
        let inner = line
            .text
            .strip_prefix("if (")
            .and_then(|text| text.strip_suffix(") {"))
            .ok_or_else(|| anyhow::anyhow!("{}: unsupported if predicate", line.number))?;
        let then_body = self.parse_block(&["}", "} else {"])?;
        let else_body = if self.peek_text() == Some("} else {") {
            self.next();
            let body = self.parse_block(&["}"])?;
            self.expect("}")?;
            body
        } else {
            self.expect("}")?;
            Vec::new()
        };
        Ok(Statement::If {
            predicate: parse_powershell_predicate(inner, line.number)?,
            then_body,
            else_body,
        })
    }
    fn parse_while(&mut self) -> Result<Statement> {
        let line = self.next().expect("while line should exist");
        let inner = line
            .text
            .strip_prefix("while (")
            .and_then(|text| text.strip_suffix(") {"))
            .ok_or_else(|| anyhow::anyhow!("{}: expected while condition", line.number))?;
        let predicate = parse_powershell_predicate(inner, line.number)?;
        let body = self.parse_block(&["}"])?;
        self.expect("}")?;
        Ok(Statement::While { predicate, body })
    }

    fn parse_switch(&mut self) -> Result<Statement> {
        let line = self.next().expect("switch line should exist");
        let value = line
            .text
            .strip_prefix("switch (")
            .and_then(|text| text.strip_suffix(") {"))
            .ok_or_else(|| anyhow::anyhow!("{}: expected switch header", line.number))?;
        let mut arms = Vec::new();
        while let Some(line) = self.peek().cloned() {
            if line.text == "}" {
                self.next();
                break;
            }
            let pattern = line
                .text
                .strip_suffix(" {")
                .ok_or_else(|| anyhow::anyhow!("{}: expected switch arm", line.number))?;
            self.next();
            let body = self.parse_block(&["}"])?;
            self.expect("}")?;
            arms.push(CaseArm {
                patterns: vec![parse_pattern(pattern)],
                body,
            });
        }
        Ok(Statement::Case {
            value: parse_value(value, line.number)?,
            arms,
        })
    }

    fn expect(&mut self, expected: &str) -> Result<()> {
        let Some(line) = self.next() else {
            bail!("expected `{expected}`, found end of input");
        };
        if line.text != expected {
            bail!(
                "{}: expected `{expected}`, got `{}`",
                line.number,
                line.text
            );
        }
        Ok(())
    }

    fn peek(&self) -> Option<&Line> {
        self.lines.get(self.index)
    }

    fn peek_text(&self) -> Option<&str> {
        self.peek().map(|line| line.text.as_str())
    }

    fn next(&mut self) -> Option<Line> {
        let line = self.lines.get(self.index).cloned();
        self.index += usize::from(line.is_some());
        line
    }
}

fn parse_simple_statement(line: &Line) -> Result<Statement> {
    if let Some((name, value)) = assignment(&line.text) {
        if let Some(argv) = value.strip_prefix("& ") {
            let argv = parse_argv(argv, line.number)?;
            return Ok(Statement::CaptureChecked { name, argv });
        }
        return Ok(Statement::Assign {
            name,
            value: parse_value(value, line.number)?,
        });
    }
    if let Some(value) = line.text.strip_prefix("Write-Output ") {
        return Ok(Statement::Print {
            value: parse_value(value, line.number)?,
        });
    }
    if let Some(value) = line.text.strip_prefix("throw ") {
        return Ok(Statement::Fail {
            value: parse_value(value, line.number)?,
        });
    }
    if line.text == "break" {
        return Ok(Statement::Break);
    }
    if let Some(seconds) = line.text.strip_prefix("Start-Sleep -Seconds ") {
        return Ok(Statement::Sleep {
            seconds: seconds
                .parse()
                .map_err(|_| anyhow::anyhow!("{}: invalid sleep seconds", line.number))?,
        });
    }
    if let Some(argv) = line.text.strip_prefix("& ") {
        return Ok(Statement::ExecChecked {
            argv: parse_argv(argv, line.number)?,
        });
    }
    if is_valid_name(&line.text) {
        return Ok(Statement::ExecChecked {
            argv: vec![Value::Literal {
                text: line.text.clone(),
            }],
        });
    }
    bail!(
        "{}: unsupported PowerShell statement: {}",
        line.number,
        line.text
    )
}
