use crate::core::transpile::ast::{ArgvSpec, Predicate, ToolInvocation, Value};

pub(super) fn sed_capture_expr(pattern: &str, group: usize) -> String {
    let delimiter = sed_delimiter(pattern);
    format!(
        "s{delimiter}.*{}.*{delimiter}\\{group}{delimiter}p",
        pattern.replace(delimiter, &format!("\\{delimiter}"))
    )
}

fn sed_delimiter(pattern: &str) -> char {
    ['#', '@', '%', '|', ';', ':']
        .into_iter()
        .find(|delimiter| !pattern.contains(*delimiter))
        .unwrap_or('#')
}

pub(super) fn argv_spec_name(spec: &ArgvSpec) -> String {
    match &spec.default {
        Some(default) => format!("{}={default}", spec.name),
        None => spec.name.clone(),
    }
}

pub(super) fn option_name(name: &str) -> String {
    format!("--{}", name.replace('_', "-"))
}

pub(super) fn join_values(values: &[Value], format: fn(&Value) -> String) -> String {
    values.iter().map(format).collect::<Vec<_>>().join(" ")
}

pub(super) fn bash_tool_command(invocation: &ToolInvocation) -> String {
    let mut parts = vec!["runseal".to_string(), "@tool".to_string()];
    parts.extend(invocation.path.iter().map(|part| sh_quote(part)));
    parts.extend(invocation.argv.iter().map(bash_value));
    parts.join(" ")
}

pub(super) fn generated_header(target: &str, source_name: Option<&str>) -> String {
    let source = source_name.unwrap_or("<memory>");
    format!("# Generated by runseal @transpile from {source} for {target}.\n")
}

pub(super) fn seal_predicate(predicate: &Predicate) -> String {
    match predicate {
        Predicate::Empty { value } => format!("empty {}", seal_value(value)),
        Predicate::NotEmpty { value } => format!("not_empty {}", seal_value(value)),
        Predicate::Eq { left, right } => format!("eq {} {}", seal_value(left), seal_value(right)),
        Predicate::Neq { left, right } => format!("neq {} {}", seal_value(left), seal_value(right)),
        Predicate::IntLt { left, right } => {
            format!("lt {} {}", seal_value(left), seal_value(right))
        }
        Predicate::IntLte { left, right } => {
            format!("lte {} {}", seal_value(left), seal_value(right))
        }
        Predicate::IntGt { left, right } => {
            format!("gt {} {}", seal_value(left), seal_value(right))
        }
        Predicate::IntGte { left, right } => {
            format!("gte {} {}", seal_value(left), seal_value(right))
        }
        Predicate::JsonEmpty { value } => format!("json_empty {}", seal_value(value)),
        Predicate::JsonNotEmpty { value } => format!("json_not_empty {}", seal_value(value)),
        Predicate::FileExists { path } => format!("file_exists {}", seal_value(path)),
        Predicate::DirExists { path } => format!("dir_exists {}", seal_value(path)),
        Predicate::ToolExists { name } => format!("tool_exists {name}"),
    }
}

pub(super) fn bash_predicate(predicate: &Predicate) -> String {
    match predicate {
        Predicate::Empty { value } => format!("[ -z {} ]", bash_value(value)),
        Predicate::NotEmpty { value } => format!("[ -n {} ]", bash_value(value)),
        Predicate::Eq { left, right } => {
            format!("[ {} = {} ]", bash_value(left), bash_value(right))
        }
        Predicate::Neq { left, right } => {
            format!("[ {} != {} ]", bash_value(left), bash_value(right))
        }
        Predicate::IntLt { left, right } => {
            format!("[ {} -lt {} ]", bash_int_value(left), bash_int_value(right))
        }
        Predicate::IntLte { left, right } => {
            format!("[ {} -le {} ]", bash_int_value(left), bash_int_value(right))
        }
        Predicate::IntGt { left, right } => {
            format!("[ {} -gt {} ]", bash_int_value(left), bash_int_value(right))
        }
        Predicate::IntGte { left, right } => {
            format!("[ {} -ge {} ]", bash_int_value(left), bash_int_value(right))
        }
        Predicate::JsonEmpty { value } => {
            format!(
                "[ \"$(runseal @tool json empty {})\" = true ]",
                bash_value(value)
            )
        }
        Predicate::JsonNotEmpty { value } => {
            format!(
                "[ \"$(runseal @tool json empty {})\" = false ]",
                bash_value(value)
            )
        }
        Predicate::FileExists { path } => format!("[ -f {} ]", bash_value(path)),
        Predicate::DirExists { path } => format!("[ -d {} ]", bash_value(path)),
        Predicate::ToolExists { name } => format!("command -v {} >/dev/null 2>&1", sh_quote(name)),
    }
}

pub(super) fn seal_value(value: &Value) -> String {
    match value {
        Value::Literal { text } => sh_quote(text),
        Value::Var { name } => format!("${name}"),
        Value::Env { name } => format!("${{{name}}}"),
        Value::EnvDefault { name, default } => format!("${{{name}:-{default}}}"),
        Value::Concat { parts } => {
            let inner = parts
                .iter()
                .map(|part| match part {
                    Value::Literal { text } => text.clone(),
                    _ => seal_value(part),
                })
                .collect::<String>();
            double_quote(&inner)
        }
    }
}

pub(super) fn bash_value(value: &Value) -> String {
    match value {
        Value::Literal { text } => sh_quote(text),
        Value::Var { name } => format!("\"${name}\""),
        Value::Env { name } => format!("\"${{{name}}}\""),
        Value::EnvDefault { name, default } => format!("\"${{{name}:-{default}}}\""),
        Value::Concat { parts } => double_quote(
            &parts
                .iter()
                .map(|part| match part {
                    Value::Literal { text } => text.clone(),
                    Value::Var { name } => format!("${name}"),
                    Value::Env { name } => format!("${{{name}}}"),
                    Value::EnvDefault { name, default } => format!("${{{name}:-{default}}}"),
                    Value::Concat { .. } => bash_value(part),
                })
                .collect::<String>(),
        ),
    }
}

pub(super) fn bash_int_value(value: &Value) -> String {
    match value {
        Value::Var { name } => format!("${name}"),
        Value::Env { name } => format!("${{{name}}}"),
        Value::EnvDefault { name, default } => format!("${{{name}:-{default}}}"),
        Value::Literal { text } => sh_quote(text),
        Value::Concat { .. } => bash_value(value),
    }
}

pub(super) fn sh_quote(value: &str) -> String {
    if value.is_empty() {
        return "''".to_string();
    }
    if value.bytes().all(|byte| {
        byte.is_ascii_alphanumeric() || matches!(byte, b'_' | b'.' | b'/' | b'-' | b':')
    }) {
        return value.to_string();
    }
    format!("'{}'", value.replace('\'', "'\"'\"'"))
}

fn double_quote(value: &str) -> String {
    format!("\"{}\"", value.replace('"', "\\\""))
}
