use crate::core::transpile::ast::{Predicate, Value};

pub(super) fn option_name(name: &str) -> String {
    format!("--{}", name.replace('_', "-"))
}

pub(super) fn join_values(values: &[Value], format: fn(&Value) -> String) -> String {
    values.iter().map(format).collect::<Vec<_>>().join(" ")
}

pub(super) fn generated_header(target: &str, source_name: Option<&str>) -> String {
    let source = source_name.unwrap_or("<memory>");
    format!("# Generated by runseal @transpile from {source} for {target}.\n")
}

pub(super) fn bash_predicate(predicate: &Predicate) -> String {
    match predicate {
        Predicate::Empty { value } => format!("[ -z {} ]", bash_value(value)),
        Predicate::NotEmpty { value } => format!("[ -n {} ]", bash_value(value)),
        Predicate::Eq { left, right } => {
            format!("[ {} = {} ]", bash_value(left), bash_value(right))
        }
        Predicate::Neq { left, right } => {
            format!("[ {} != {} ]", bash_value(left), bash_value(right))
        }
        Predicate::IntLt { left, right } => {
            format!("[ {} -lt {} ]", bash_int_value(left), bash_int_value(right))
        }
        Predicate::IntLte { left, right } => {
            format!("[ {} -le {} ]", bash_int_value(left), bash_int_value(right))
        }
        Predicate::IntGt { left, right } => {
            format!("[ {} -gt {} ]", bash_int_value(left), bash_int_value(right))
        }
        Predicate::IntGte { left, right } => {
            format!("[ {} -ge {} ]", bash_int_value(left), bash_int_value(right))
        }
        Predicate::JsonEmpty { value } => {
            format!(
                "[ \"$(runseal @tool json empty {})\" = true ]",
                bash_value(value)
            )
        }
        Predicate::JsonNotEmpty { value } => {
            format!(
                "[ \"$(runseal @tool json empty {})\" = false ]",
                bash_value(value)
            )
        }
        Predicate::FileExists { path } => format!("[ -f {} ]", bash_value(path)),
        Predicate::DirExists { path } => format!("[ -d {} ]", bash_value(path)),
    }
}

pub(super) fn seal_value(value: &Value) -> String {
    match value {
        Value::Literal { text } => sh_quote(text),
        Value::Var { name } => format!("${name}"),
        Value::Args => "\"$@\"".to_string(),
        Value::Env { name } => format!("${{{name}}}"),
        Value::EnvDefault { name, default } => format!("${{{name}:-{default}}}"),
        Value::Concat { parts } => {
            let inner = parts
                .iter()
                .map(|part| match part {
                    Value::Literal { text } => text.clone(),
                    Value::Args => "$@".to_string(),
                    _ => seal_value(part),
                })
                .collect::<String>();
            double_quote(&inner)
        }
    }
}

pub(super) fn bash_value(value: &Value) -> String {
    match value {
        Value::Literal { text } => sh_quote(text),
        Value::Var { name } => format!("\"${name}\""),
        Value::Args => "\"$@\"".to_string(),
        Value::Env { name } => format!("\"${{{name}}}\""),
        Value::EnvDefault { name, default } => format!("\"${{{name}:-{default}}}\""),
        Value::Concat { parts } => double_quote(
            &parts
                .iter()
                .map(|part| match part {
                    Value::Literal { text } => text.clone(),
                    Value::Var { name } => format!("${name}"),
                    Value::Args => "$@".to_string(),
                    Value::Env { name } => format!("${{{name}}}"),
                    Value::EnvDefault { name, default } => format!("${{{name}:-{default}}}"),
                    Value::Concat { .. } => bash_value(part),
                })
                .collect::<String>(),
        ),
    }
}

pub(super) fn bash_int_value(value: &Value) -> String {
    match value {
        Value::Var { name } => format!("${name}"),
        Value::Args => "\"$@\"".to_string(),
        Value::Env { name } => format!("${{{name}}}"),
        Value::EnvDefault { name, default } => format!("${{{name}:-{default}}}"),
        Value::Literal { text } => sh_quote(text),
        Value::Concat { .. } => bash_value(value),
    }
}

pub(super) fn sh_quote(value: &str) -> String {
    if value.is_empty() {
        return "''".to_string();
    }
    if value.bytes().all(|byte| {
        byte.is_ascii_alphanumeric()
            || matches!(byte, b'_' | b'.' | b'/' | b'-' | b':')
            || byte == b'@'
    }) {
        return value.to_string();
    }
    format!("'{}'", value.replace('\'', "'\"'\"'"))
}

fn double_quote(value: &str) -> String {
    format!("\"{}\"", value.replace('"', "\\\""))
}
