import { booleanOption, helpRequested, parseArgs, requireNoPositionals } from "@/lib/cli.ts";
import { cmd } from "@/lib/std/cmd.ts";
import { fs } from "@/lib/std/fs.ts";
import { io } from "@/lib/std/io.ts";
import { path } from "@/lib/std/path.ts";

function usage(): void {
  io.print("Usage: runseal :init [--force]");
  io.print("");
  io.print("Validate the repository and install generated git hooks.");
  io.print("");
  io.print("Options:");
  io.print("  --force    back up custom hooks before replacing them");
}

async function requireTool(name: string): Promise<void> {
  if (!(await cmd.exists(name))) {
    io.fail(`init: missing required tool: ${name}`);
  }
}

async function requirePath(root: string, relPath: string): Promise<void> {
  if (!(await fs.file.exists(path.join(root, relPath)))) {
    io.fail(`init: missing required path: ${relPath}`);
  }
}

async function prepareHook(path: string): Promise<void> {
  if (!(await fs.file.exists(path))) {
    return;
  }
  const generated = await fs.file.containsAny(path, [
    "runseal init hook",
    "runseal bootstrap hook",
  ]);
  if (generated) {
    return;
  }
  if (!force) {
    io.fail(
      `init: ${path} already exists and was not generated by runseal init; rerun with --force to back it up and replace it`,
    );
  }
  const backup = await fs.file.backup.numbered(path);
  io.print(`backed up existing hook to ${backup}`);
}

const args = parseArgs(Deno.args, { boolean: ["force", "help", "h"] });
requireNoPositionals(args, "init", { allowHelp: true });
if (helpRequested(args)) {
  usage();
  Deno.exit(0);
}
const force = booleanOption(args, "force");

io.print("==> resolving repository");
const root = await cmd.text("git", ["rev-parse", "--show-toplevel"]);
const gitDir = await cmd.text("git", ["rev-parse", "--absolute-git-dir"]);
const hooksDir = path.join(gitDir, "hooks");
const preCommit = path.join(hooksDir, "pre-commit");
const commitMsg = path.join(hooksDir, "commit-msg");
io.print(`repository: ${root}`);

io.print("==> checking required tools");
for (
  const tool of [
    "git",
    "deno",
    "python3",
    "cargo",
    "runseal",
    "flavor",
    "sh",
    "bash",
    "sed",
    "grep",
  ]
) {
  await requireTool(tool);
}
io.print("ok: git, deno, python3, cargo, runseal, flavor, sh, bash, sed, grep");

io.print("==> checking repository entrypoints");
for (
  const path of [
    "Cargo.toml",
    "Cargo.lock",
    "deno.lock",
    "flavor.toml",
    "manage.sh",
    "manage.ps1",
    "runseal.toml",
    ".runseal/deno.json",
    ".runseal/hooks/pre-commit",
    ".runseal/hooks/commit-msg",
    ".runseal/lib/cli.ts",
    ".runseal/lib/hash.ts",
    ".runseal/lib/std/cmd.ts",
    ".runseal/lib/std/env.ts",
    ".runseal/lib/std/fs.ts",
    ".runseal/lib/std/io.ts",
    ".runseal/lib/std/json.ts",
    ".runseal/lib/std/path.ts",
    ".runseal/lib/std/runseal.ts",
    ".runseal/lib/version.ts",
    ".runseal/templates/cloudflare.env",
    ".runseal/wrappers/cloudflare.ts",
    ".runseal/wrappers/guard.ts",
    ".runseal/wrappers/init.ts",
    ".runseal/wrappers/pr.ts",
    ".runseal/wrappers/release.ts",
    ".github/workflows/guard.yml",
    ".github/workflows/release-beta.yml",
    ".github/workflows/release-stable.yml",
    ".github/scripts/release/assets/checksums.sh",
    ".github/scripts/release/assets/package.sh",
    ".github/scripts/release/assets/package.ps1",
    ".github/scripts/release/assets/verify.sh",
    ".github/scripts/release/github/cleanup-artifacts.sh",
    ".github/scripts/release/metadata/beta.py",
    ".github/scripts/release/metadata/stable.py",
    ".github/scripts/release/r2/check.sh",
    ".github/scripts/release/r2/publish.sh",
    ".github/scripts/release/r2/summary.sh",
    ".github/scripts/release/r2/verify.sh",
    ".github/scripts/release/smoke/smoke.sh",
    ".github/scripts/release/smoke/smoke.ps1",
  ]
) {
  await requirePath(root, path);
}
io.print("ok: repository entrypoints");

io.print("==> installing git hooks");
await fs.dir.ensure(hooksDir, "700");

await prepareHook(preCommit);
await Deno.copyFile(".runseal/hooks/pre-commit", preCommit);
await fs.file.chmodIfUnix(preCommit, "755");
io.print(`installed ${preCommit}`);

await prepareHook(commitMsg);
await Deno.copyFile(".runseal/hooks/commit-msg", commitMsg);
await fs.file.chmodIfUnix(commitMsg, "755");
io.print(`installed ${commitMsg}`);

await cmd.run("deno", ["--version"], { stdout: "null" });
io.print("development environment ready");
