import {
  commandExists,
  fail,
  fileExists,
  pathJoin,
  print,
  run,
  runseal,
  runsealText,
  runText,
} from "../lib/runseal.ts";

let force = false;
let help = false;
const args = [...Deno.args];
while (args.length > 0) {
  const arg = args.shift()!;
  switch (arg) {
    case "--force":
      force = true;
      break;
    case "--":
      args.length = 0;
      break;
    case "-h":
    case "--help":
    case "help":
      help = true;
      break;
    default:
      fail(`unknown option: ${arg}`);
  }
}

function usage(): void {
  print("Usage: runseal :init [--force]");
  print("");
  print("Validate the repository and install generated git hooks.");
  print("");
  print("Options:");
  print("  --force    back up custom hooks before replacing them");
}

async function requireTool(name: string): Promise<void> {
  if (!(await commandExists(name))) {
    fail(`init: missing required tool: ${name}`);
  }
}

async function requirePath(root: string, path: string): Promise<void> {
  if (!(await fileExists(pathJoin(root, path)))) {
    fail(`init: missing required path: ${path}`);
  }
}

async function prepareHook(path: string): Promise<void> {
  if (!(await fileExists(path))) {
    return;
  }
  const generated = await runsealText([
    "@tool",
    "fs",
    "contains-any",
    path,
    "runseal init hook",
    "runseal bootstrap hook",
  ]);
  if (generated === "true") {
    return;
  }
  if (!force) {
    fail(
      `init: ${path} already exists and was not generated by runseal init; rerun with --force to back it up and replace it`,
    );
  }
  const backup = await runsealText(["@tool", "fs", "backup-numbered", path]);
  print(`backed up existing hook to ${backup}`);
}

if (help) {
  usage();
  Deno.exit(0);
}

print("==> resolving repository");
const root = await runText("git", ["rev-parse", "--show-toplevel"]);
const gitDir = await runText("git", ["rev-parse", "--absolute-git-dir"]);
const hooksDir = pathJoin(gitDir, "hooks");
const preCommit = pathJoin(hooksDir, "pre-commit");
const commitMsg = pathJoin(hooksDir, "commit-msg");
print(`repository: ${root}`);

print("==> checking required tools");
for (
  const tool of [
    "git",
    "deno",
    "python3",
    "cargo",
    "runseal",
    "flavor",
    "sh",
    "bash",
    "sed",
    "grep",
  ]
) {
  await requireTool(tool);
}
print("ok: git, deno, python3, cargo, runseal, flavor, sh, bash, sed, grep");

print("==> checking repository entrypoints");
for (
  const path of [
    "Cargo.toml",
    "Cargo.lock",
    "flavor.toml",
    "manage.sh",
    "manage.ps1",
    "runseal.toml",
    ".runseal/deno.json",
    ".runseal/hooks/pre-commit",
    ".runseal/hooks/commit-msg",
    ".runseal/lib/runseal.ts",
    ".runseal/wrappers/cloudflare.ts",
    ".runseal/wrappers/guard.ts",
    ".runseal/wrappers/init.ts",
    ".runseal/wrappers/pr.ts",
    ".runseal/wrappers/release.ts",
    ".github/workflows/guard.yml",
    ".github/workflows/release-beta.yml",
    ".github/workflows/release-stable.yml",
    ".github/scripts/release/assets/checksums.sh",
    ".github/scripts/release/assets/package.sh",
    ".github/scripts/release/assets/package.ps1",
    ".github/scripts/release/assets/verify.sh",
    ".github/scripts/release/github/cleanup-artifacts.sh",
    ".github/scripts/release/metadata/beta.py",
    ".github/scripts/release/metadata/stable.py",
    ".github/scripts/release/r2/check.sh",
    ".github/scripts/release/r2/publish.sh",
    ".github/scripts/release/r2/summary.sh",
    ".github/scripts/release/r2/verify.sh",
    ".github/scripts/release/smoke/smoke.sh",
    ".github/scripts/release/smoke/smoke.ps1",
  ]
) {
  await requirePath(root, path);
}
print("ok: repository entrypoints");

print("==> installing git hooks");
await runseal(["@tool", "fs", "mkdir", hooksDir, "700"]);

await prepareHook(preCommit);
await Deno.copyFile(".runseal/hooks/pre-commit", preCommit);
await runseal(["@tool", "fs", "chmod", preCommit, "755"]);
print(`installed ${preCommit}`);

await prepareHook(commitMsg);
await Deno.copyFile(".runseal/hooks/commit-msg", commitMsg);
await runseal(["@tool", "fs", "chmod", commitMsg, "755"]);
print(`installed ${commitMsg}`);

await run("deno", ["--version"], { stdout: "null" });
print("development environment ready");
