use anyhow::{Result, bail};

use super::ast::{CaseArm, Item, Predicate, Program, Statement, Value};
use super::lower::lower_functions;

#[derive(Debug, Clone)]
struct Line {
    number: usize,
    text: String,
}

struct Parser {
    lines: Vec<Line>,
    index: usize,
}

pub(crate) fn parse_powershell(source: &str) -> Result<Program> {
    Parser::new(source).parse_program()
}

impl Parser {
    fn new(source: &str) -> Self {
        let lines = source
            .lines()
            .enumerate()
            .filter_map(|(index, line)| {
                let text = strip_comment(line).trim().to_string();
                if text.is_empty()
                    || text.starts_with("# Generated by ")
                    || text == "$ErrorActionPreference = 'Stop'"
                {
                    return None;
                }
                Some(Line {
                    number: index + 1,
                    text,
                })
            })
            .collect();
        Self { lines, index: 0 }
    }

    fn parse_program(mut self) -> Result<Program> {
        let mut items = Vec::new();
        while self.peek().is_some() {
            if self
                .peek_text()
                .is_some_and(|text| text.starts_with("function "))
            {
                items.push(self.parse_function()?);
            } else {
                items.push(Item::Statement {
                    statement: self.parse_statement()?,
                });
            }
        }
        Ok(lower_functions(Program { version: 1, items }))
    }

    fn parse_function(&mut self) -> Result<Item> {
        let line = self.next().expect("function line should exist");
        let name = line
            .text
            .strip_prefix("function ")
            .and_then(|text| text.strip_suffix(" {"))
            .ok_or_else(|| anyhow::anyhow!("{}: expected function header", line.number))?;
        validate_name(name, line.number)?;
        let body = self.parse_block(&["}"])?;
        self.expect("}")?;
        Ok(Item::Function {
            name: name.to_string(),
            body,
        })
    }

    fn parse_block(&mut self, terminators: &[&str]) -> Result<Vec<Statement>> {
        let mut body = Vec::new();
        while let Some(line) = self.peek() {
            if terminators
                .iter()
                .any(|terminator| line.text == *terminator)
            {
                break;
            }
            if line.text == "break" {
                self.next();
                continue;
            }
            body.push(self.parse_statement()?);
        }
        Ok(body)
    }

    fn parse_statement(&mut self) -> Result<Statement> {
        let Some(line) = self.peek().cloned() else {
            bail!("unexpected end of input");
        };
        if line.text.starts_with("if ") {
            return self.parse_if();
        }
        if line.text.starts_with("switch ") {
            return self.parse_switch();
        }
        self.next();
        parse_simple_statement(&line)
    }

    fn parse_if(&mut self) -> Result<Statement> {
        let line = self.next().expect("if line should exist");
        let value = line
            .text
            .strip_prefix("if ([string]::IsNullOrEmpty(")
            .and_then(|text| text.strip_suffix(")) {"))
            .ok_or_else(|| anyhow::anyhow!("{}: unsupported if predicate", line.number))?;
        let then_body = self.parse_block(&["}"])?;
        self.expect("}")?;
        Ok(Statement::If {
            predicate: Predicate::Empty {
                value: parse_value(value, line.number)?,
            },
            then_body,
            else_body: Vec::new(),
        })
    }

    fn parse_switch(&mut self) -> Result<Statement> {
        let line = self.next().expect("switch line should exist");
        let value = line
            .text
            .strip_prefix("switch (")
            .and_then(|text| text.strip_suffix(") {"))
            .ok_or_else(|| anyhow::anyhow!("{}: expected switch header", line.number))?;
        let mut arms = Vec::new();
        while let Some(line) = self.peek().cloned() {
            if line.text == "}" {
                self.next();
                break;
            }
            let pattern = line
                .text
                .strip_suffix(" {")
                .ok_or_else(|| anyhow::anyhow!("{}: expected switch arm", line.number))?;
            self.next();
            let body = self.parse_block(&["}"])?;
            self.expect("}")?;
            arms.push(CaseArm {
                patterns: vec![parse_pattern(pattern)],
                body,
            });
        }
        Ok(Statement::Case {
            value: parse_value(value, line.number)?,
            arms,
        })
    }

    fn expect(&mut self, expected: &str) -> Result<()> {
        let Some(line) = self.next() else {
            bail!("expected `{expected}`, found end of input");
        };
        if line.text != expected {
            bail!(
                "{}: expected `{expected}`, got `{}`",
                line.number,
                line.text
            );
        }
        Ok(())
    }

    fn peek(&self) -> Option<&Line> {
        self.lines.get(self.index)
    }

    fn peek_text(&self) -> Option<&str> {
        self.peek().map(|line| line.text.as_str())
    }

    fn next(&mut self) -> Option<Line> {
        let line = self.lines.get(self.index).cloned();
        self.index += usize::from(line.is_some());
        line
    }
}

fn parse_simple_statement(line: &Line) -> Result<Statement> {
    if let Some((name, value)) = assignment(&line.text) {
        if let Some(argv) = value.strip_prefix("& ") {
            return Ok(Statement::CaptureChecked {
                name,
                argv: split_exprs(argv, line.number)?
                    .iter()
                    .map(|arg| parse_value(arg, line.number))
                    .collect::<Result<Vec<_>>>()?,
            });
        }
        return Ok(Statement::Assign {
            name,
            value: parse_value(value, line.number)?,
        });
    }
    if let Some(value) = line.text.strip_prefix("Write-Output ") {
        return Ok(Statement::Print {
            value: parse_value(value, line.number)?,
        });
    }
    if let Some(value) = line.text.strip_prefix("throw ") {
        return Ok(Statement::Fail {
            value: parse_value(value, line.number)?,
        });
    }
    if let Some(argv) = line.text.strip_prefix("& ") {
        return Ok(Statement::ExecChecked {
            argv: split_exprs(argv, line.number)?
                .iter()
                .map(|arg| parse_value(arg, line.number))
                .collect::<Result<Vec<_>>>()?,
        });
    }
    if is_valid_name(&line.text) {
        return Ok(Statement::ExecChecked {
            argv: vec![Value::Literal {
                text: line.text.clone(),
            }],
        });
    }
    bail!(
        "{}: unsupported PowerShell statement: {}",
        line.number,
        line.text
    )
}

fn assignment(text: &str) -> Option<(String, &str)> {
    let (name, value) = text.split_once(" = ")?;
    let name = name.strip_prefix('$')?;
    is_valid_name(name).then_some((name.to_string(), value))
}

fn parse_value(text: &str, line: usize) -> Result<Value> {
    let text = text.trim();
    if let Some(value) = text
        .strip_prefix('\'')
        .and_then(|value| value.strip_suffix('\''))
    {
        return Ok(Value::Literal {
            text: value.replace("''", "'"),
        });
    }
    if let Some((name, default)) = env_default(text) {
        validate_name(name, line)?;
        return Ok(Value::EnvDefault {
            name: name.to_string(),
            default: default.to_string(),
        });
    }
    if let Some(name) = text.strip_prefix("$env:") {
        validate_name(name, line)?;
        return Ok(Value::Env {
            name: name.to_string(),
        });
    }
    if let Some(name) = text.strip_prefix('$') {
        validate_name(name, line)?;
        return Ok(Value::Var {
            name: name.to_string(),
        });
    }
    if let Some(inner) = text
        .strip_prefix('(')
        .and_then(|value| value.strip_suffix(')'))
        && inner.contains(" + ")
    {
        return Ok(Value::Concat {
            parts: split_concat(inner, line)?
                .iter()
                .map(|part| parse_value(part, line))
                .collect::<Result<Vec<_>>>()?,
        });
    }
    bail!("{line}: unsupported PowerShell value: {text}")
}

fn env_default(text: &str) -> Option<(&str, &str)> {
    let inner = text.strip_prefix("$(if ($env:")?;
    let (name, rest) = inner.split_once(") { $env:")?;
    let (name2, rest) = rest.split_once(" } else { ")?;
    if name != name2 {
        return None;
    }
    let default = rest.strip_suffix(" })")?;
    let default = default.strip_prefix('\'')?.strip_suffix('\'')?;
    Some((name, default))
}

fn split_exprs(text: &str, line: usize) -> Result<Vec<String>> {
    split_top_level(text, line, ' ')
}

fn split_concat(text: &str, line: usize) -> Result<Vec<String>> {
    split_top_level(text, line, '+').map(|items| {
        items
            .into_iter()
            .map(|item| item.trim().to_string())
            .collect()
    })
}

fn split_top_level(text: &str, line: usize, delimiter: char) -> Result<Vec<String>> {
    let mut items = Vec::new();
    let mut current = String::new();
    let mut quote = false;
    let mut depth = 0usize;
    for ch in text.chars() {
        match ch {
            '\'' => {
                quote = !quote;
                current.push(ch);
            }
            '(' if !quote => {
                depth += 1;
                current.push(ch);
            }
            ')' if !quote => {
                depth = depth.saturating_sub(1);
                current.push(ch);
            }
            ch if ch == delimiter && !quote && depth == 0 => {
                if !current.trim().is_empty() {
                    items.push(current.trim().to_string());
                    current.clear();
                }
            }
            _ => current.push(ch),
        }
    }
    if quote {
        bail!("{line}: unterminated PowerShell string");
    }
    if !current.trim().is_empty() {
        items.push(current.trim().to_string());
    }
    Ok(items)
}

fn strip_comment(line: &str) -> String {
    let mut output = String::new();
    let mut quote = false;
    for ch in line.chars() {
        match ch {
            '\'' => {
                quote = !quote;
                output.push(ch);
            }
            '#' if !quote => break,
            _ => output.push(ch),
        }
    }
    output
}

fn parse_pattern(pattern: &str) -> String {
    if pattern == "Default" {
        return "*".to_string();
    }
    pattern
        .strip_prefix('\'')
        .and_then(|value| value.strip_suffix('\''))
        .unwrap_or(pattern)
        .to_string()
}

fn validate_name(name: &str, line: usize) -> Result<()> {
    if !is_valid_name(name) {
        bail!("{line}: invalid PowerShell name: {name}");
    }
    Ok(())
}

fn is_valid_name(name: &str) -> bool {
    let mut bytes = name.bytes();
    matches!(bytes.next(), Some(byte) if byte.is_ascii_alphabetic() || byte == b'_')
        && bytes.all(|byte| byte.is_ascii_alphanumeric() || byte == b'_')
}
